# Generated by Django 6.0.1 on 2026-02-25 09:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import smart_selects.db_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliance', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='tenants.site')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('employee_id', models.CharField(max_length=25)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('position', models.CharField(max_length=30)),
                ('hire_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('left', 'Left Company')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff', to='human_resources.department')),
                ('site', models.ForeignKey(blank=True, help_text='Site this staff member belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='tenants.site')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_profile', to=settings.AUTH_USER_MODEL, verbose_name='Login Account')),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('annual', 'Annual Leave'), ('sick', 'Sick Leave'), ('compassionate', 'Compassionate Leave'), ('unpaid', 'Unpaid Leave'), ('special', 'Special Leave')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days', models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0.5)])),
                ('reason', models.CharField(blank=True, max_length=80)),
                ('approved_by', models.CharField(blank=True, max_length=50)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('document', models.FileField(blank=True, upload_to='leave_docs/')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='human_resources.person')),
            ],
            options={
                'verbose_name_plural': 'Leave Records',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Induction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('induction_date', models.DateField(default=django.utils.timezone.now)),
                ('next_review_date', models.DateField(blank=True, help_text='When induction needs to be reviewed/updated', null=True)),
                ('induction_provided', models.CharField(max_length=200)),
                ('facilitator', models.CharField(blank=True, max_length=100)),
                ('document', models.FileField(blank=True, upload_to='induction_docs/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_policy', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='policy_category', chained_model_field='category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='induction_policy_links', to='compliance.policycompliancedocument', verbose_name='Policy Document')),
                ('linked_sop', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='sop_category', chained_model_field='category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='induction_sop_links', to='compliance.sopscompliancedocument', verbose_name='SOP Document')),
                ('policy_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='induction_policy_categories', to='compliance.policycategory', verbose_name='Policy Category')),
                ('sop_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='induction_sop_categories', to='compliance.sopscategory', verbose_name='SOP Category')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inductions', to='human_resources.person')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Inductions',
            },
        ),
        migrations.CreateModel(
            name='PositionLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position_levels', to='tenants.site')),
            ],
            options={
                'verbose_name': 'Position Level',
                'verbose_name_plural': 'Position Levels',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='person',
            name='position_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff', to='human_resources.positionlevel'),
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_date', models.DateField(default=django.utils.timezone.now)),
                ('next_review_date', models.DateField(blank=True, help_text='When training needs to be reviewed/updated', null=True)),
                ('training_provided', models.CharField(max_length=200)),
                ('trainer', models.CharField(blank=True, max_length=100)),
                ('document', models.FileField(blank=True, upload_to='training_docs/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_policy', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='policy_category', chained_model_field='category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_policy_links', to='compliance.policycompliancedocument', verbose_name='Policy Document')),
                ('linked_sop', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='sop_category', chained_model_field='category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_sop_links', to='compliance.sopscompliancedocument', verbose_name='SOP Document')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='human_resources.person')),
                ('policy_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_policy_categories', to='compliance.policycategory', verbose_name='Policy Category')),
                ('sop_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_sop_categories', to='compliance.sopscategory', verbose_name='SOP Category')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Training Records',
            },
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('site', 'employee_id')},
        ),
    ]
