# Generated by Django 6.0.1 on 2026-03-10 09:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='induction',
            name='document',
            field=models.FileField(blank=True, upload_to='induction_docs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='leave',
            name='document',
            field=models.FileField(blank=True, upload_to='leave_docs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='training',
            name='document',
            field=models.FileField(blank=True, upload_to='training_docs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
