# Generated by Django 6.0.1 on 2026-01-25 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0002_person_site'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='tenants.site'),
        ),
        migrations.AddField(
            model_name='positionlevel',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position_levels', to='tenants.site'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='positionlevel',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
