# Generated by Django 6.0.1 on 2026-02-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0003_department_site_positionlevel_site_and_more'),
        ('tenants', '0008_add_site_to_unitofmeasure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='employee_id',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('site', 'employee_id')},
        ),
    ]
