# Generated by Django 6.0.1 on 2026-02-10 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0004_alter_person_email_alter_person_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'Staff', 'verbose_name_plural': 'Staff'},
        ),
    ]
