# Generated by Django 6.0.1 on 2026-02-25 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryComplianceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factory_documents', to='tenants.site')),
            ],
            options={
                'verbose_name': 'Factory Document',
                'verbose_name_plural': 'Factory Documents',
            },
        ),
        migrations.CreateModel(
            name='FactoryComplianceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='compliance/factory/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='compliance.factorycompliancedocument')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policy_categories', to='tenants.site')),
            ],
            options={
                'verbose_name': 'Policy Category',
                'verbose_name_plural': 'Policy Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PolicyComplianceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy_docs', to='compliance.policycategory', verbose_name='Category')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policy_documents', to='tenants.site')),
            ],
            options={
                'verbose_name': 'Policy Document',
                'verbose_name_plural': 'Policy Documents',
                'unique_together': {('category', 'title')},
            },
        ),
        migrations.CreateModel(
            name='PolicyComplianceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='compliance/policy/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='compliance.policycompliancedocument')),
            ],
        ),
        migrations.CreateModel(
            name='ProductComplianceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_documents', to='tenants.site')),
            ],
            options={
                'verbose_name': 'Product Document',
                'verbose_name_plural': 'Product Documents',
            },
        ),
        migrations.CreateModel(
            name='ProductComplianceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='compliance/product/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='compliance.productcompliancedocument')),
            ],
        ),
        migrations.CreateModel(
            name='ReportSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_sheets', to='tenants.site')),
            ],
            options={
                'verbose_name': 'Report Sheet',
                'verbose_name_plural': 'Report Sheets',
            },
        ),
        migrations.CreateModel(
            name='ReportSheetAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='compliance/report_sheets/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='compliance.reportsheet')),
            ],
        ),
        migrations.CreateModel(
            name='SopsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sops_categories', to='tenants.site')),
            ],
            options={
                'verbose_name': 'SOP Category',
                'verbose_name_plural': 'SOP Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SopsComplianceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sops_documents', to='compliance.sopscategory', verbose_name='Category')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sops_compliance_documents', to='tenants.site')),
            ],
            options={
                'verbose_name': 'SOP Document',
                'verbose_name_plural': 'SOP Documents',
                'unique_together': {('category', 'title')},
            },
        ),
        migrations.CreateModel(
            name='SopsComplianceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='compliance/sops/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='compliance.sopscompliancedocument')),
            ],
        ),
        migrations.CreateModel(
            name='SpecSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spec_sheets', to='tenants.site')),
            ],
            options={
                'verbose_name': 'Spec Sheet',
                'verbose_name_plural': 'Spec Sheets',
            },
        ),
        migrations.CreateModel(
            name='SpecSheetAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='compliance/spec_sheets/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='compliance.specsheet')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='compliance.policycategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Policy Title',
                'verbose_name_plural': 'Policy Titles',
                'ordering': ['category', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SopsTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='compliance.sopscategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'SOP Title',
                'verbose_name_plural': 'SOP Titles',
                'ordering': ['category', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
    ]
