# Generated by Django 6.0.1 on 2026-03-10 09:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factorycomplianceattachment',
            name='file',
            field=models.FileField(upload_to='compliance/factory/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='policycomplianceattachment',
            name='file',
            field=models.FileField(upload_to='compliance/policy/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='productcomplianceattachment',
            name='file',
            field=models.FileField(upload_to='compliance/product/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='reportsheetattachment',
            name='file',
            field=models.FileField(upload_to='compliance/report_sheets/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='sopscomplianceattachment',
            name='file',
            field=models.FileField(upload_to='compliance/sops/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='specsheetattachment',
            name='file',
            field=models.FileField(upload_to='compliance/spec_sheets/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
