# Generated by Django 6.0.1 on 2026-01-25 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factorycompliancedocument',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factory_documents', to='tenants.site'),
        ),
        migrations.AddField(
            model_name='policycompliancedocument',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policy_documents', to='tenants.site'),
        ),
        migrations.AddField(
            model_name='productcompliancedocument',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_documents', to='tenants.site'),
        ),
        migrations.AddField(
            model_name='sopscompliancedocument',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sops_compliance_documents', to='tenants.site'),
        ),
        migrations.AlterField(
            model_name='policycompliancedocument',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy_docs', to='compliance.policycategory', verbose_name='Category'),
        ),
    ]
