# Generated by Django 6.0.1 on 2026-01-25 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_factorycompliancedocument_site_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policycategory',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policy_categories', to='tenants.site'),
        ),
        migrations.AddField(
            model_name='sopscategory',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sops_categories', to='tenants.site'),
        ),
        migrations.AlterField(
            model_name='policycategory',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sopscategory',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
