# Generated by Django 6.0.1 on 2026-02-03 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0003_policycategory_site_sopscategory_site_and_more'),
        ('tenants', '0005_alter_usersite_hq_username_alter_usersite_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spec_sheets', to='tenants.site')),
            ],
            options={
                'verbose_name': 'Spec Sheet',
                'verbose_name_plural': 'Spec Sheets',
            },
        ),
        migrations.CreateModel(
            name='SpecSheetAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='compliance/spec_sheets/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='compliance.specsheet')),
            ],
        ),
    ]
