# Generated by Django 6.0.1 on 2026-02-10 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0004_specsheet_specsheetattachment'),
        ('tenants', '0008_add_site_to_unitofmeasure'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_sheets', to='tenants.site')),
            ],
            options={
                'verbose_name': 'Report Sheet',
                'verbose_name_plural': 'Report Sheets',
            },
        ),
        migrations.CreateModel(
            name='ReportSheetAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='compliance/report_sheets/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='compliance.reportsheet')),
            ],
        ),
    ]
