# Generated by Django 6.0.1 on 2026-02-25 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Requested At')),
                ('object_id', models.PositiveIntegerField(verbose_name='Object ID')),
                ('object_repr', models.CharField(help_text='String representation of the object at time of request', max_length=500, verbose_name='Object Description')),
                ('reason', models.TextField(blank=True, help_text='Why should this archived item be permanently deleted?', verbose_name='Reason for Deletion')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='Handled At')),
                ('admin_notes', models.TextField(blank=True, help_text='Notes from the administrator about this request', verbose_name='Admin Notes')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Type')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletion_requests_handled', to=settings.AUTH_USER_MODEL, verbose_name='Handled By')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletion_requests_made', to=settings.AUTH_USER_MODEL, verbose_name='Requested By')),
            ],
            options={
                'verbose_name': 'Deletion Request',
                'verbose_name_plural': 'Deletion Requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
