# Generated by Django 6.0.1 on 2026-02-25 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly name (auto-generated from name)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('admin_background', models.ImageField(blank=True, help_text='Background image displayed on the admin dashboard for this site (JPEG/PNG).', null=True, upload_to='sites/backgrounds/', verbose_name='Admin Background Image')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hq_user', models.BooleanField(default=False, help_text='HQ users can access /hq/ dashboard and ALL sites. Site users cannot access HQ.')),
                ('hq_username', models.CharField(blank=True, help_text='Unique HQ login username. Only for HQ users.', max_length=150, null=True, unique=True)),
                ('hq_password', models.CharField(blank=True, help_text='HQ login password (encrypted with PBKDF2). Only for HQ users.', max_length=255, null=True)),
                ('is_manager', models.BooleanField(default=False, help_text='Site Manager')),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('assigned_site', models.ForeignKey(blank=True, help_text='Site this user belongs to (leave blank for HQ users)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_users', to='tenants.site')),
                ('user', models.ForeignKey(blank=True, help_text='Django user (required for site users, optional for HQ users)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Site Assignment',
                'verbose_name_plural': 'User Site Assignments',
            },
        ),
    ]
