# Generated by Django 6.0.1 on 2026-01-25 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(help_text="URL identifier (e.g., 'windhoek')", unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hq_user', models.BooleanField(default=False, help_text='HQ users can access /hq/ dashboard and ALL sites')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('assigned_site', models.ForeignKey(blank=True, help_text='Site this user belongs to (leave blank for HQ users)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_users', to='tenants.site')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='site_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Site Assignment',
                'verbose_name_plural': 'User Site Assignments',
            },
        ),
    ]
