# Generated by Django 6.0.1 on 2026-03-10 09:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='admin_background',
            field=models.ImageField(blank=True, help_text='Background image displayed on the admin dashboard for this site (JPEG/PNG).', null=True, upload_to='sites/backgrounds/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])], verbose_name='Admin Background Image'),
        ),
    ]
