# Generated by Django 6.0.1 on 2026-01-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='admin_background',
            field=models.ImageField(blank=True, help_text='Background image displayed on the admin dashboard for this site (JPEG/PNG).', null=True, upload_to='sites/backgrounds/', verbose_name='Admin Background Image'),
        ),
    ]
