# Generated by Django 6.0.1 on 2026-03-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_site_admin_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersite',
            name='email',
            field=models.EmailField(blank=True, default='', help_text="User's email address. Used as Reply-To when sending documents.", max_length=254),
        ),
    ]
