# Generated by Django 6.0.1 on 2026-01-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_add_admin_background_to_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='usersite',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
