# Generated by Django 6.0.1 on 2026-02-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_add_is_archived_to_site_usersite'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersite',
            name='hq_password',
            field=models.CharField(blank=True, help_text='HQ login password (encrypted with PBKDF2). Only for HQ users.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usersite',
            name='hq_username',
            field=models.CharField(blank=True, help_text='Unique HQ login username (encrypted). Only for HQ users.', max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usersite',
            name='is_hq_user',
            field=models.BooleanField(default=False, help_text='HQ users can access /hq/ dashboard and ALL sites. Site users cannot access HQ.'),
        ),
    ]
