# Generated by Django 6.0.1 on 2026-02-03 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_usersite_hq_password_usersite_hq_username_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersite',
            name='hq_username',
            field=models.CharField(blank=True, help_text='Unique HQ login username. Only for HQ users.', max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usersite',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Django user (required for site users, optional for HQ users)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
