# Generated by Django 6.0.1 on 2026-02-03 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_alter_usersite_hq_username_alter_usersite_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly name (auto-generated from name)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='usersite',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Django user (required for site users, optional for HQ users)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
