# Generated by Django 6.0.1 on 2026-02-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_add_site_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersite',
            name='is_manager',
            field=models.BooleanField(default=False, help_text='Manager status for site-level approvals (Approval + Deletion Requests). Site managers have full site auth but NO HQ access. Only applies to site users (is_hq_user=False).'),
        ),
    ]
