# Generated by Django 6.0.1 on 2026-02-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_usersite_is_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersite',
            name='is_manager',
            field=models.BooleanField(default=False, help_text='Site manager: has similar control to superuser but ONLY for their assigned site. No HQ access. Only applies to site users.'),
        ),
    ]
