# Generated by Django 6.0.1 on 2026-02-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_add_site_to_unitofmeasure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersite',
            name='is_manager',
            field=models.BooleanField(default=False, help_text='Site Manager'),
        ),
    ]
