# Generated by Django 6.0.1 on 2026-02-25 09:23

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Ingredient Type',
                'verbose_name_plural': 'Ingredient Types',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, max_length=100, null=True, verbose_name='SKU')),
                ('size', models.CharField(blank=True, max_length=50, null=True, verbose_name='Size')),
                ('requires_nsi_nrcs_certification', models.BooleanField(default=True, help_text='Check if this product requires NSI or NRCS certification after manufacturing', verbose_name='Requires NSI / NRCS Certification')),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='tenants.site')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['product_name'],
            },
        ),
        migrations.CreateModel(
            name='MainProductComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_usage_per_production_unit', models.DecimalField(decimal_places=4, default=1, max_digits=12, verbose_name='Standard usage per production unit')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.stockcategory', verbose_name='Category')),
                ('stock_item', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='sub_category', chained_model_field='sub_category', on_delete=django.db.models.deletion.CASCADE, to='inventory.stockitem', verbose_name='Stock Item')),
                ('sub_category', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='category', chained_model_field='category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.stocksubcategory', verbose_name='Sub Category')),
                ('unit_of_measure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.unitofmeasure', verbose_name='Unit of Measure')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_product_components', to='product_details.product')),
            ],
            options={
                'verbose_name': 'Main Product Component',
                'verbose_name_plural': 'Main Product Components',
                'ordering': ['product', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='tenants.site')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product_details.productcategory'),
        ),
        migrations.CreateModel(
            name='ProductComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_per_pallet', models.DecimalField(decimal_places=4, default=1, max_digits=12, verbose_name='Usage per Pallet')),
                ('standard_usage_per_production_unit', models.DecimalField(decimal_places=4, default=1, max_digits=12, verbose_name='Usage per unit')),
                ('is_primary_packaging', models.BooleanField(default=False, verbose_name='Primary')),
                ('is_secondary_packaging', models.BooleanField(default=False, verbose_name='Secondary')),
                ('is_pallet', models.BooleanField(default=False, verbose_name='Pallet')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.stockcategory', verbose_name='Category')),
                ('main_stock_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_stock_items', to='product_details.productcomponent', verbose_name='Main Stock Item')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='product_details.product')),
                ('stock_item', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='sub_category', chained_model_field='sub_category', on_delete=django.db.models.deletion.CASCADE, to='inventory.stockitem', verbose_name='Stock Item')),
                ('sub_category', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='category', chained_model_field='category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.stocksubcategory', verbose_name='Sub Category')),
                ('unit_of_measure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.unitofmeasure', verbose_name='Unit of Measure')),
            ],
            options={
                'verbose_name': 'Product Component',
                'verbose_name_plural': 'Product Components',
                'ordering': ['product', 'category'],
            },
        ),
        migrations.CreateModel(
            name='ProductRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(help_text='Enter the recipe name (e.g., Brown Sauce, Cream Sauce)', max_length=255, verbose_name='Recipe Name')),
                ('standard_usage_per_production_unit', models.DecimalField(decimal_places=4, default=1, max_digits=12, verbose_name='Usage per unit')),
                ('measure_unit', models.CharField(choices=[('L', 'Litres (L)'), ('Kg', 'Kilograms (Kg)')], default='L', max_length=10, verbose_name='Measure Unit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='product_details.product')),
            ],
            options={
                'verbose_name': 'Product Recipe',
                'verbose_name_plural': 'Product Recipes',
                'ordering': ['product', 'recipe_name'],
            },
        ),
        migrations.CreateModel(
            name='ProductRecipeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_usage_per_production_unit', models.DecimalField(decimal_places=4, default=1, max_digits=12, verbose_name='Usage per unit')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.stockcategory', verbose_name='Category')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product_details.productrecipe')),
                ('stock_item', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='sub_category', chained_model_field='sub_category', on_delete=django.db.models.deletion.CASCADE, to='inventory.stockitem', verbose_name='Stock Item')),
                ('sub_category', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='category', chained_model_field='category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.stocksubcategory', verbose_name='Sub Category')),
                ('unit_of_measure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.unitofmeasure', verbose_name='Unit of Measure')),
            ],
            options={
                'verbose_name': 'Recipe Item',
                'verbose_name_plural': 'Recipe Items',
                'ordering': ['recipe', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RecipeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.site', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Recipe Category',
                'verbose_name_plural': 'Recipe Categories',
                'ordering': ['name'],
                'unique_together': {('name', 'site')},
            },
        ),
        migrations.AddField(
            model_name='productrecipe',
            name='recipe_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_details.recipecategory', verbose_name='Recipe Category'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('site', 'sku')},
        ),
        migrations.AlterUniqueTogether(
            name='productrecipe',
            unique_together={('product', 'recipe_category', 'recipe_name')},
        ),
    ]
