# Generated by Django 6.0.1 on 2026-02-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_details', '0002_product_site_productcategory_site_and_more'),
        ('tenants', '0008_add_site_to_unitofmeasure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SKU'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('site', 'sku')},
        ),
    ]
