# Generated by Django 6.0.1 on 2026-02-15 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('product_details', '0003_alter_product_sku_alter_product_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipecategory',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Site that owns this recipe category', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recipe_categories', to='tenants.site'),
        ),
        migrations.AlterUniqueTogether(
            name='recipecategory',
            unique_together={('name', 'site')},
        ),
    ]
