# Generated by Django 6.0.1 on 2026-02-16 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_details', '0004_recipecategory_site_alter_recipecategory_unique_together'),
        ('tenants', '0009_alter_usersite_is_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipecategory',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='recipecategory',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.site', verbose_name='Site'),
        ),
    ]
