# Generated by Django 6.0.1 on 2026-02-25 09:23

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commercial', '0002_initial'),
        ('costing', '0002_initial'),
        ('inventory', '0001_initial'),
        ('manufacturing', '0001_initial'),
        ('product_details', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedproducttransaction',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finished_transactions', to='manufacturing.batch', verbose_name='Production Batch'),
        ),
        migrations.AddField(
            model_name='finishedproducttransaction',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commercial.client', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='finishedproducttransaction',
            name='from_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finished_outgoing', to='commercial.warehouse', verbose_name='From Warehouse'),
        ),
        migrations.AddField(
            model_name='finishedproducttransaction',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finished_product_transactions', to='tenants.site'),
        ),
        migrations.AddField(
            model_name='finishedproducttransaction',
            name='to_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finishedproduct_to_warehouse', to='commercial.warehouse', verbose_name='Warehouse'),
        ),
        migrations.AddField(
            model_name='hqpolineitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_details.productcategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='hqpolineitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_details.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='pickingslip',
            name='billing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='picking_slip', to='costing.billingdocumentheader', verbose_name='Billing Document'),
        ),
        migrations.AddField(
            model_name='pickingslip',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picking_slips', to='tenants.site'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Site this purchase order belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='tenants.site'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='commercial.supplier', verbose_name='Supplier'),
        ),
        migrations.AddField(
            model_name='hqpolineitem',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hq_line_items', to='inventory.purchaseorder', verbose_name='Purchase Order'),
        ),
        migrations.AddField(
            model_name='purchaseorderlineitem',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='inventory.purchaseorder', verbose_name='Purchase Order'),
        ),
        migrations.AddField(
            model_name='stockcategory',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_categories', to='tenants.site'),
        ),
        migrations.AddField(
            model_name='purchaseorderlineitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.stockcategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Select category to filter available suppliers', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.stockcategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='container',
            name='item_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.stockcategory', verbose_name='Item Category'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.stockcategory', verbose_name='Item Category'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Site this stock item belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='tenants.site'),
        ),
        migrations.AddField(
            model_name='recipestockitembalance',
            name='stock_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_stock_balances_by_date', to='inventory.stockitem', verbose_name='Recipe Stock Item'),
        ),
        migrations.AddField(
            model_name='purchaseorderlineitem',
            name='stock_item',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='sub_category', chained_model_field='sub_category', on_delete=django.db.models.deletion.CASCADE, related_name='po_line_items', to='inventory.stockitem', verbose_name='Stock Item'),
        ),
        migrations.AddField(
            model_name='packagingbalance',
            name='stock_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packaging_balances_by_date', to='inventory.stockitem', verbose_name='Packaging Item'),
        ),
        migrations.AddField(
            model_name='container',
            name='stock_item',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='sub_category', chained_model_field='sub_category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.stockitem', verbose_name='Stock Item'),
        ),
        migrations.AddField(
            model_name='amendment',
            name='stock_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='inventory.stockitem'),
        ),
        migrations.AddField(
            model_name='stocksubcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='inventory.stockcategory'),
        ),
        migrations.AddField(
            model_name='stocksubcategory',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_subcategories', to='tenants.site'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='sub_category',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='category', chained_model_field='category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.stocksubcategory', verbose_name='Sub Category'),
        ),
        migrations.AddField(
            model_name='purchaseorderlineitem',
            name='sub_category',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='category', chained_model_field='category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.stocksubcategory', verbose_name='Sub Category'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='sub_category',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='category', chained_model_field='category', help_text='Select sub-category to further filter suppliers', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.stocksubcategory', verbose_name='Sub Category'),
        ),
        migrations.AddField(
            model_name='container',
            name='sub_category',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='item_category', chained_model_field='category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.stocksubcategory', verbose_name='Sub category'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transactions', to='manufacturing.batch', verbose_name='Linked Production Batch'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.stockcategory', verbose_name='Item Category'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transactions', to='inventory.container', verbose_name='Linked Container'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_transactions', to='tenants.site'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='stock_item',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='sub_category', chained_model_field='sub_category', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.stockitem', verbose_name='Stock Item'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='sub_category',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='category', chained_model_field='category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.stocksubcategory'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='supplier',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='sub_category', chained_model_field='sub_category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='commercial.supplier', verbose_name='Supplier'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='transporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commercial.transporter', verbose_name='Transporter'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commercial.warehouse', verbose_name='Warehouse'),
        ),
        migrations.AddField(
            model_name='unitofmeasure',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Site this unit belongs to. Leave blank for HQ units.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units_of_measure', to='tenants.site'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='unit_of_measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='inventory.unitofmeasure', verbose_name='Unit of Measure'),
        ),
        migrations.AddIndex(
            model_name='finishedproducttransaction',
            index=models.Index(fields=['batch', 'date'], name='inventory_f_batch_i_45c24c_idx'),
        ),
        migrations.AddIndex(
            model_name='finishedproducttransaction',
            index=models.Index(fields=['transaction_type'], name='inventory_f_transac_69a7eb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recipestockitembalance',
            unique_together={('production_date', 'stock_item', 'batch_ref_type', 'batch_ref')},
        ),
        migrations.AlterUniqueTogether(
            name='packagingbalance',
            unique_together={('production_date', 'stock_item', 'batch_ref_type', 'batch_ref')},
        ),
        migrations.AddConstraint(
            model_name='unitofmeasure',
            constraint=models.UniqueConstraint(fields=('site', 'name'), name='unique_unit_name_per_site'),
        ),
        migrations.AddConstraint(
            model_name='unitofmeasure',
            constraint=models.UniqueConstraint(fields=('site', 'abbreviation'), name='unique_unit_abbr_per_site'),
        ),
    ]
