# Generated by Django 6.0.1 on 2026-01-23 08:30

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0003_add_purchase_order_models'),
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='PO Number')),
                ('order_type', models.CharField(choices=[('Local', 'Local'), ('Import', 'Import')], default='Local', max_length=10, verbose_name='Order Type')),
                ('currency', models.CharField(choices=[('R', 'Rand (R)'), ('NAD', 'Namibian Dollar (NAD)'), ('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)')], default='R', max_length=5, verbose_name='Currency')),
                ('order_date', models.DateField(verbose_name='Order Date')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Sent', 'Sent'), ('Acknowledged', 'Acknowledged'), ('Received', 'Received'), ('Closed', 'Closed')], default='Draft', max_length=20, verbose_name='Status')),
                ('create_po', models.BooleanField(default=False, verbose_name='Create PO')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='commercial.supplier', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'ordering': ['-order_date', '-po_number'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Quantity to Order')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, help_text='Price per unit excluding transport, pulled from last stock transaction', max_digits=12, verbose_name='Unit Price (Excl Transport)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.stockcategory', verbose_name='Category')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='inventory.purchaseorder', verbose_name='Purchase Order')),
                ('stock_item', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='sub_category', chained_model_field='sub_category', on_delete=django.db.models.deletion.CASCADE, related_name='po_line_items', to='inventory.stockitem', verbose_name='Stock Item')),
                ('sub_category', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='category', chained_model_field='category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.stocksubcategory', verbose_name='Sub Category')),
            ],
            options={
                'verbose_name': 'PO Line Item',
                'verbose_name_plural': 'PO Line Items',
                'ordering': ['id'],
            },
        ),
    ]
