# Generated by Django 6.0.1 on 2026-03-10 09:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='clearing_doc',
            field=models.FileField(blank=True, null=True, upload_to='container_docs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png'])], verbose_name='Clearing Document'),
        ),
        migrations.AlterField(
            model_name='container',
            name='commission_doc',
            field=models.FileField(blank=True, null=True, upload_to='container_docs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png'])], verbose_name='Commission Document'),
        ),
        migrations.AlterField(
            model_name='container',
            name='deposit_doc',
            field=models.FileField(blank=True, null=True, upload_to='container_docs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png'])], verbose_name='Proforma/Quote/PO'),
        ),
        migrations.AlterField(
            model_name='container',
            name='duty_doc',
            field=models.FileField(blank=True, null=True, upload_to='container_docs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png'])], verbose_name='Duty Document'),
        ),
        migrations.AlterField(
            model_name='container',
            name='final_payment_doc',
            field=models.FileField(blank=True, null=True, upload_to='container_docs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png'])], verbose_name='Invoice'),
        ),
        migrations.AlterField(
            model_name='container',
            name='fob_price_doc',
            field=models.FileField(blank=True, null=True, upload_to='container_docs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png'])], verbose_name='Invoice'),
        ),
        migrations.AlterField(
            model_name='container',
            name='invoice_doc',
            field=models.FileField(blank=True, null=True, upload_to='container_docs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png'])], verbose_name='Invoice Document'),
        ),
        migrations.AlterField(
            model_name='container',
            name='permit_doc',
            field=models.FileField(blank=True, null=True, upload_to='container_docs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png'])], verbose_name='Permit Document'),
        ),
        migrations.AlterField(
            model_name='container',
            name='po_doc',
            field=models.FileField(blank=True, null=True, upload_to='container_docs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png'])], verbose_name='PO Document'),
        ),
        migrations.AlterField(
            model_name='container',
            name='transport_doc',
            field=models.FileField(blank=True, null=True, upload_to='container_docs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png'])], verbose_name='Transport Document'),
        ),
        migrations.AlterField(
            model_name='pickingslip',
            name='picking_slip_pdf',
            field=models.FileField(blank=True, null=True, upload_to='picking_slips/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Picking Slip PDF'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='invoice_document',
            field=models.FileField(blank=True, null=True, upload_to='invoices/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png'])], verbose_name='Invoice Document (PDF/DOC)'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='sauce_sheet',
            field=models.FileField(blank=True, null=True, upload_to='sauce_sheets/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png'])], verbose_name='Sauce Mixing Sheet (PDF/DOC)'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='transporter_document',
            field=models.FileField(blank=True, null=True, upload_to='transporter_docs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png'])], verbose_name='Transporter Document (PDF/DOC)'),
        ),
    ]
