# Generated by Django 6.0.1 on 2026-01-23 08:47

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0003_add_purchase_order_models'),
        ('inventory', '0003_add_purchase_order_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Select category to filter available suppliers', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.stockcategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='sub_category',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='category', chained_model_field='category', help_text='Select sub-category to further filter suppliers', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.stocksubcategory', verbose_name='Sub Category'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='sub_category', chained_model_field='sub_category', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='commercial.supplier', verbose_name='Supplier'),
        ),
    ]
