# Generated by Django 5.2.7 on 2026-01-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_add_po_category_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='vat_percentage',
            field=models.DecimalField(decimal_places=2, default=15, help_text='VAT percentage - default 15%', max_digits=5, verbose_name='VAT (%)'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(blank=True, help_text='Auto-generated if left blank. Can be manually edited.', max_length=20, unique=True, verbose_name='PO Number'),
        ),
    ]
