# Generated by Django 5.2.7 on 2026-01-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_purchaseorder_vat_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='PO Number'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='vat_percentage',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=5, verbose_name='VAT (%)'),
        ),
    ]
