# Generated by Django 6.0.1 on 2026-01-25 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_purchaseorder_po_number_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Site this stock item belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='tenants.site'),
        ),
    ]
