# Generated by Django 6.0.1 on 2026-01-25 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_stockitem_site'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Site this purchase order belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='tenants.site'),
        ),
    ]
