# Generated by Django 6.0.1 on 2026-01-25 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_purchaseorder_site'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='tenants.site'),
        ),
        migrations.AddField(
            model_name='finishedproducttransaction',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finished_product_transactions', to='tenants.site'),
        ),
        migrations.AddField(
            model_name='pickingslip',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picking_slips', to='tenants.site'),
        ),
        migrations.AddField(
            model_name='stockcategory',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_categories', to='tenants.site'),
        ),
        migrations.AddField(
            model_name='stocksubcategory',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_subcategories', to='tenants.site'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_transactions', to='tenants.site'),
        ),
        migrations.AlterField(
            model_name='stockcategory',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='stocksubcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
