# Generated by Django 6.0.1 on 2026-01-28 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0006_companydetails_site'),
        ('inventory', '0009_container_site_finishedproducttransaction_site_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='commercial.supplier', verbose_name='Supplier'),
        ),
    ]
