# Generated by Django 6.0.1 on 2026-02-06 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0006_companydetails_site'),
        ('inventory', '0010_change_supplier_to_regular_fk'),
        ('product_details', '0002_product_site_productcategory_site_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='commercial.supplier', verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='purchaseorderlineitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Unit Price (Excl Transport)'),
        ),
        migrations.CreateModel(
            name='HQPOLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Qty for PO')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Price for PO')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_details.productcategory', verbose_name='Category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_details.product', verbose_name='Product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hq_line_items', to='inventory.purchaseorder', verbose_name='Purchase Order')),
            ],
            options={
                'verbose_name': 'HQ PO Line Item',
                'verbose_name_plural': 'HQ PO Line Items',
                'ordering': ['id'],
            },
        ),
    ]
