# Generated by Django 6.0.1 on 2026-02-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_purchaseorder_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='is_hq_order',
            field=models.BooleanField(db_index=True, default=False, verbose_name='HQ Order'),
        ),
    ]
