# Generated by Django 6.0.1 on 2026-02-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_purchaseorder_is_hq_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='hqpolineitem',
            name='size',
            field=models.CharField(blank=True, help_text='Auto-fills from product', max_length=50, null=True, verbose_name='Size'),
        ),
        migrations.AddField(
            model_name='hqpolineitem',
            name='sku',
            field=models.CharField(blank=True, help_text='Auto-fills from product, editable', max_length=100, null=True, verbose_name='SKU'),
        ),
    ]
