# Generated by Django 6.0.1 on 2026-02-07 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_hqpolineitem_size_hqpolineitem_sku'),
        ('product_details', '0002_product_site_productcategory_site_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hqpolineitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_details.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='hqpolineitem',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='hqpolineitem',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SKU'),
        ),
    ]
