# Generated by Django 6.0.1 on 2026-02-10 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_hqpolineitem_product_alter_hqpolineitem_size_and_more'),
        ('tenants', '0008_add_site_to_unitofmeasure'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitofmeasure',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Site this unit belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units_of_measure', to='tenants.site'),
        ),
    ]
