# Generated by Django 6.0.1 on 2026-02-10 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_add_site_to_unitofmeasure'),
        ('tenants', '0008_add_site_to_unitofmeasure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitofmeasure',
            name='abbreviation',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Site this unit belongs to. Leave blank for HQ units.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units_of_measure', to='tenants.site'),
        ),
        migrations.AddConstraint(
            model_name='unitofmeasure',
            constraint=models.UniqueConstraint(fields=('site', 'name'), name='unique_unit_name_per_site'),
        ),
        migrations.AddConstraint(
            model_name='unitofmeasure',
            constraint=models.UniqueConstraint(fields=('site', 'abbreviation'), name='unique_unit_abbr_per_site'),
        ),
    ]
