# Generated by Django 6.0.1 on 2026-01-22 17:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchCosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Selling Price = stock price incl VAT + overhead per unit + salary per unit + markup.', max_digits=12, verbose_name='Selling Price')),
                ('use_markup', models.BooleanField(default=False, help_text='Check to apply percentage markup', verbose_name='Use Markup %')),
                ('markup_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Markup %')),
                ('use_markup_per_unit', models.BooleanField(default=True, help_text='Check to apply fixed markup', verbose_name='Use Markup per Unit')),
                ('markup_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Markup per Unit')),
                ('stock_item_price_use', models.DecimalField(decimal_places=2, default=0, help_text='Price to use for costing calculations', max_digits=12, verbose_name='Stock Item Price Use')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date Created')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this batch costing', null=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name': 'Batch Costing',
                'verbose_name_plural': 'Batch Costing',
                'ordering': ['-production_date'],
            },
        ),
        migrations.CreateModel(
            name='BatchPriceApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_price_per_unit', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Batch Price per Unit')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approved')),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Batch Price Approval',
                'verbose_name_plural': 'Batch Price Approvals',
            },
        ),
        migrations.CreateModel(
            name='BillingDocumentHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_dates_text', models.TextField(blank=True, default='', help_text='Comma-separated production dates')),
                ('base_number', models.CharField(max_length=20, unique=True, verbose_name='Base Number')),
                ('bill_per_pallet', models.BooleanField(default=False, verbose_name='pallet')),
                ('bill_per_secondary', models.BooleanField(default=False, verbose_name='secondary packaging')),
                ('bill_per_primary', models.BooleanField(default=False, verbose_name='primary packaging')),
                ('billing_date', models.DateField(default=django.utils.timezone.now, verbose_name='Billing date')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due date')),
                ('from_currency', models.CharField(choices=[('R', 'R'), ('NAD', 'NAD'), ('USD', '$'), ('EUR', '€')], default='NAD', max_length=3, verbose_name='From currency')),
                ('to_currency', models.CharField(choices=[('R', 'R'), ('NAD', 'NAD'), ('USD', '$'), ('EUR', '€')], default='R', max_length=3, verbose_name='To currency')),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1, help_text='Rate from from-currency to to-currency.', max_digits=12, verbose_name='Exchange rate')),
                ('transport_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Transport cost')),
                ('create_quote', models.BooleanField(default=False, verbose_name='Create Quote')),
                ('create_proforma', models.BooleanField(default=False, verbose_name='Create Proforma')),
                ('create_invoice', models.BooleanField(default=True, verbose_name='Create Invoice')),
                ('create_picking_slip', models.BooleanField(default=False, verbose_name='Create Picking Slip')),
                ('create_delivery_note', models.BooleanField(default=False, verbose_name='Create Delivery Note')),
                ('qty_for_invoice_data', models.JSONField(blank=True, default=dict)),
                ('quote_created', models.BooleanField(default=False, editable=False)),
                ('proforma_created', models.BooleanField(default=False, editable=False)),
                ('invoice_created', models.BooleanField(default=False, editable=False)),
                ('picking_slip_created', models.BooleanField(default=False, editable=False)),
                ('delivery_note_created', models.BooleanField(default=False, editable=False)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name': 'Billing',
                'verbose_name_plural': 'Billing',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='OverheadCosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('production_units', models.PositiveIntegerField(default=0, verbose_name='Production Units (Month)')),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('use_as_default', models.BooleanField(default=False, help_text='Mark this record as the default overhead costing to use', verbose_name='Use as Default')),
            ],
            options={
                'verbose_name': 'Overhead Costing',
                'verbose_name_plural': 'Overhead Costing',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='OverheadItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100, verbose_name='Overhead Item')),
                ('item_type', models.CharField(choices=[('Fixed', 'Fixed'), ('Variable', 'Variable')], max_length=10, verbose_name='Type')),
                ('per_month', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Per Month')),
            ],
            options={
                'verbose_name': 'Overhead Item',
                'verbose_name_plural': 'Overhead Items',
                'ordering': ['item_type', 'item_name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_markup', models.BooleanField(default=False, help_text='Check to apply percentage markup', verbose_name='Use Markup %')),
                ('markup_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Markup %')),
                ('use_markup_percentage', models.BooleanField(default=True, help_text='Check to apply fixed markup', verbose_name='Use Markup per Unit')),
                ('markup_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Markup per Unit')),
                ('waste_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Global waste percentage', max_digits=5, verbose_name='Waste %')),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Selling Price = Total stock items incl. VAT + Overhead price per unit + Salary price per unit + Markup (percentage or fixed per unit).', max_digits=12, verbose_name='Selling Price')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date Created')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this product costing', null=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name': 'Product Costing',
                'verbose_name_plural': 'Product Costing',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProductCostingStockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_per_unit', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Usage')),
                ('unit_of_measure', models.CharField(editable=False, max_length=10, verbose_name='Unit')),
                ('price_including_transport', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Price Inc Transport')),
                ('price_per_unit_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Price per Unit')),
                ('use_price_per_unit', models.DecimalField(decimal_places=2, default=0, help_text='Editable price to use for costing (defaults to calculated price per unit)', max_digits=12, verbose_name='Use Price per Unit')),
                ('waste_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Waste percentage for this item', max_digits=5, verbose_name='Waste %')),
                ('use_markup', models.BooleanField(default=False, help_text='Check to apply markup to this item', verbose_name='Use Markup')),
                ('markup_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Markup percentage to apply', max_digits=5, verbose_name='% Markup')),
                ('markup_per_unit', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Calculated markup amount per unit', max_digits=12, verbose_name='Markup per Unit')),
            ],
            options={
                'verbose_name': 'Product Costing Stock Item',
                'verbose_name_plural': 'Product Costing Stock Items',
            },
        ),
        migrations.CreateModel(
            name='SalaryCosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('management_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Management')),
                ('office_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Office')),
                ('production_units', models.PositiveIntegerField(default=0, verbose_name='Production Units (Month)')),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('use_as_default', models.BooleanField(default=False, help_text='Mark this record as the default salary costing to use', verbose_name='Use as Default')),
            ],
            options={
                'verbose_name': 'Salary Costing',
                'verbose_name_plural': 'Salary Costing',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SalaryPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=100, verbose_name='Position Name')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Description')),
                ('general_workers', models.IntegerField(default=0, verbose_name='General Workers')),
                ('rate_per_hour', models.DecimalField(decimal_places=2, default=25, max_digits=8, verbose_name='Rate/Hour')),
                ('qa_workers', models.IntegerField(default=0, verbose_name='QA Workers')),
                ('qa_rate_per_hour', models.DecimalField(decimal_places=2, default=50, max_digits=8, verbose_name='QA Rate/Hour')),
                ('shifts', models.IntegerField(default=1, verbose_name='Shifts per Day')),
                ('shift_hours', models.DecimalField(decimal_places=1, default=8, max_digits=4, verbose_name='Hours per Shift')),
                ('days_worked', models.DecimalField(decimal_places=1, default=20, max_digits=4, verbose_name='Days Worked')),
            ],
            options={
                'verbose_name': 'Salary Position',
                'verbose_name_plural': 'Salary Positions',
                'ordering': ['position_name'],
            },
        ),
    ]
