# Generated by Django 6.0.1 on 2026-02-25 09:23

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commercial', '0002_initial'),
        ('costing', '0001_initial'),
        ('inventory', '0001_initial'),
        ('manufacturing', '0001_initial'),
        ('product_details', '0001_initial'),
        ('tenants', '0001_initial'),
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchcosting',
            name='production_date',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_costing', to='manufacturing.production', verbose_name='Production Date'),
        ),
        migrations.AddField(
            model_name='batchcosting',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_costings', to='tenants.site'),
        ),
        migrations.AddField(
            model_name='batchpriceapproval',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_approval', to='manufacturing.batch', verbose_name='Batch'),
        ),
        migrations.AddField(
            model_name='batchpriceapproval',
            name='batch_costing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_approvals', to='costing.batchcosting', verbose_name='Batch Costing'),
        ),
        migrations.AddField(
            model_name='billingdocumentheader',
            name='batch_costings',
            field=models.ManyToManyField(blank=True, related_name='billing_headers_multi', to='costing.batchcosting', verbose_name='Product Costings (hidden)'),
        ),
        migrations.AddField(
            model_name='billingdocumentheader',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_headers', to='commercial.client', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='billingdocumentheader',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_headers', to='commercial.companydetails', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='billingdocumentheader',
            name='delivery_institution',
            field=models.ForeignKey(blank=True, help_text='Select the institution/location to deliver to for this client', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_headers', to='transport.deliverysite', verbose_name='Delivery Institution'),
        ),
        migrations.AddField(
            model_name='billingdocumentheader',
            name='import_source_site',
            field=models.ForeignKey(blank=True, help_text='The site this HQ import came from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_billing_documents', to='tenants.site', verbose_name='Source Site'),
        ),
        migrations.AddField(
            model_name='billingdocumentheader',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Site this billing document belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_documents', to='tenants.site'),
        ),
        migrations.AddField(
            model_name='billingdocumentheader',
            name='transporters',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_headers', to='commercial.transporter', verbose_name='Transporter'),
        ),
        migrations.AddField(
            model_name='billinglineitem',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_line_items', to='manufacturing.batch', verbose_name='Batch'),
        ),
        migrations.AddField(
            model_name='billinglineitem',
            name='billing_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='costing.billingdocumentheader', verbose_name='Billing Document'),
        ),
        migrations.AddField(
            model_name='billinglineitem',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Filter batches by site', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_line_items', to='tenants.site', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='investorloancosting',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Site this costing belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investor_loan_costings', to='tenants.site'),
        ),
        migrations.AddField(
            model_name='batchcosting',
            name='investor_loan_costing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='costing.investorloancosting', verbose_name='Investor / Loan Costing'),
        ),
        migrations.AddField(
            model_name='investorloanitem',
            name='header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='costing.investorloancosting'),
        ),
        migrations.AddField(
            model_name='overheadcosting',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Site this costing belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overhead_costings', to='tenants.site'),
        ),
        migrations.AddField(
            model_name='batchcosting',
            name='overhead_costing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='costing.overheadcosting', verbose_name='Overhead Costing'),
        ),
        migrations.AddField(
            model_name='overheaditem',
            name='header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='costing.overheadcosting'),
        ),
        migrations.AddField(
            model_name='productcosting',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_details.productcategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='productcosting',
            name='investor_loan_costing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='costing.investorloancosting', verbose_name='Investor / Loan Costing'),
        ),
        migrations.AddField(
            model_name='productcosting',
            name='overhead_costing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='costing.overheadcosting', verbose_name='Overhead Costing'),
        ),
        migrations.AddField(
            model_name='productcosting',
            name='product',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='category', chained_model_field='category', on_delete=django.db.models.deletion.CASCADE, to='product_details.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='productcosting',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Site this product costing belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_costings', to='tenants.site'),
        ),
        migrations.AddField(
            model_name='productcostingstockitem',
            name='product_costing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='costing.productcosting'),
        ),
        migrations.AddField(
            model_name='productcostingstockitem',
            name='stock_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.stockitem', verbose_name='Stock Item'),
        ),
        migrations.AddField(
            model_name='salarycosting',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Site this costing belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_costings', to='tenants.site'),
        ),
        migrations.AddField(
            model_name='productcosting',
            name='salary_costing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='costing.salarycosting', verbose_name='Salary Costing'),
        ),
        migrations.AddField(
            model_name='batchcosting',
            name='salary_costing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='costing.salarycosting', verbose_name='Salary Costing'),
        ),
        migrations.AddField(
            model_name='salaryposition',
            name='header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='costing.salarycosting'),
        ),
        migrations.AlterUniqueTogether(
            name='batchpriceapproval',
            unique_together={('batch_costing', 'batch')},
        ),
        migrations.AlterUniqueTogether(
            name='billinglineitem',
            unique_together={('billing_document', 'batch')},
        ),
    ]
