# Generated by Django 6.0.1 on 2026-01-22 17:30

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commercial', '0002_initial'),
        ('costing', '0001_initial'),
        ('inventory', '0001_initial'),
        ('manufacturing', '0001_initial'),
        ('product_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchcosting',
            name='production_date',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_costing', to='manufacturing.production', verbose_name='Production Date'),
        ),
        migrations.AddField(
            model_name='batchpriceapproval',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_approval', to='manufacturing.batch', verbose_name='Batch'),
        ),
        migrations.AddField(
            model_name='batchpriceapproval',
            name='batch_costing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_approvals', to='costing.batchcosting', verbose_name='Batch Costing'),
        ),
        migrations.AddField(
            model_name='billingdocumentheader',
            name='batch_costings',
            field=models.ManyToManyField(blank=True, related_name='billing_headers_multi', to='costing.batchcosting', verbose_name='Product Costings (hidden)'),
        ),
        migrations.AddField(
            model_name='billingdocumentheader',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_headers', to='commercial.client', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='billingdocumentheader',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_headers', to='commercial.companydetails', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='billingdocumentheader',
            name='transporters',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_headers', to='commercial.transporter', verbose_name='Transporter'),
        ),
        migrations.AddField(
            model_name='batchcosting',
            name='overhead_costing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='costing.overheadcosting', verbose_name='Overhead Costing'),
        ),
        migrations.AddField(
            model_name='overheaditem',
            name='header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='costing.overheadcosting'),
        ),
        migrations.AddField(
            model_name='productcosting',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_details.productcategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='productcosting',
            name='overhead_costing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='costing.overheadcosting', verbose_name='Overhead Costing'),
        ),
        migrations.AddField(
            model_name='productcosting',
            name='product',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='category', chained_model_field='category', on_delete=django.db.models.deletion.CASCADE, to='product_details.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='productcostingstockitem',
            name='product_costing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='costing.productcosting'),
        ),
        migrations.AddField(
            model_name='productcostingstockitem',
            name='stock_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.stockitem', verbose_name='Stock Item'),
        ),
        migrations.AddField(
            model_name='productcosting',
            name='salary_costing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='costing.salarycosting', verbose_name='Salary Costing'),
        ),
        migrations.AddField(
            model_name='batchcosting',
            name='salary_costing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='costing.salarycosting', verbose_name='Salary Costing'),
        ),
        migrations.AddField(
            model_name='salaryposition',
            name='header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='costing.salarycosting'),
        ),
        migrations.AlterUniqueTogether(
            name='batchpriceapproval',
            unique_together={('batch_costing', 'batch')},
        ),
    ]
