# Generated by Django 6.0.1 on 2026-08-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchcosting',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Selling Price = stock price excl VAT + overhead per unit + salary per unit + investor/loan per unit + markup.', max_digits=12, verbose_name='Selling Price'),
        ),
        migrations.AlterField(
            model_name='productcosting',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Selling Price = Total stock items excl. VAT + Overhead price per unit + Salary price per unit + Investor/Loan price per unit + Markup (% or fixed per unit).', max_digits=12, verbose_name='Selling Price'),
        ),
    ]
