# Generated by Django 6.0.1 on 2026-01-23 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchcosting',
            name='overhead_price_per_unit_snapshot',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="Captured overhead price per unit at time of first save. Won't change if default overhead is updated.", max_digits=12, null=True, verbose_name='Overhead Price/Unit (Snapshot)'),
        ),
        migrations.AddField(
            model_name='batchcosting',
            name='salary_price_per_unit_snapshot',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="Captured salary price per unit at time of first save. Won't change if default salary is updated.", max_digits=12, null=True, verbose_name='Salary Price/Unit (Snapshot)'),
        ),
        migrations.AddField(
            model_name='productcosting',
            name='overhead_price_per_unit_snapshot',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Captured overhead price per unit. Can be updated via confirmation when default changes.', max_digits=12, null=True, verbose_name='Overhead Price/Unit (Snapshot)'),
        ),
        migrations.AddField(
            model_name='productcosting',
            name='salary_price_per_unit_snapshot',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Captured salary price per unit. Can be updated via confirmation when default changes.', max_digits=12, null=True, verbose_name='Salary Price/Unit (Snapshot)'),
        ),
    ]
