# Generated by Django 6.0.1 on 2026-01-25 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0003_add_costing_snapshot_fields'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingdocumentheader',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Site this billing document belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_documents', to='tenants.site'),
        ),
        migrations.AddField(
            model_name='overheadcosting',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Site this costing belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overhead_costings', to='tenants.site'),
        ),
        migrations.AddField(
            model_name='productcosting',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Site this product costing belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_costings', to='tenants.site'),
        ),
        migrations.AddField(
            model_name='salarycosting',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Site this costing belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_costings', to='tenants.site'),
        ),
    ]
