# Generated by Django 6.0.1 on 2026-02-05 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0005_batchcosting_site'),
        ('tenants', '0006_add_site_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingdocumentheader',
            name='import_source_site',
            field=models.ForeignKey(blank=True, help_text='Original site this billing document was imported from (for HQ imports)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_billing_documents', to='tenants.site'),
        ),
    ]
