# Generated by Django 6.0.1 on 2026-02-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0006_billingdocumentheader_import_source_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingdocumentheader',
            name='import_source_invoice_number',
            field=models.CharField(blank=True, help_text='Original invoice number from the source site', max_length=20, null=True),
        ),
    ]
