# Generated by Django 6.0.1 on 2026-02-05 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0007_billingdocumentheader_import_source_invoice_number'),
        ('manufacturing', '0007_production_id_alter_batch_production_and_more'),
        ('tenants', '0006_add_site_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingdocumentheader',
            name='import_source_invoice_number',
            field=models.CharField(blank=True, default='', help_text='Original invoice number from the source site', max_length=100, verbose_name='Source Invoice Number'),
        ),
        migrations.AlterField(
            model_name='billingdocumentheader',
            name='import_source_site',
            field=models.ForeignKey(blank=True, help_text='The site this HQ import came from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_billing_documents', to='tenants.site', verbose_name='Source Site'),
        ),
        migrations.CreateModel(
            name='BillingLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_for_invoice', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Qty for Invoice')),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, help_text='Price per unit', max_digits=12, verbose_name='Selling Price')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_line_items', to='manufacturing.batch', verbose_name='Batch')),
                ('billing_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='costing.billingdocumentheader', verbose_name='Billing Document')),
            ],
            options={
                'verbose_name': 'Billing Line Item',
                'verbose_name_plural': 'Billing Line Items',
                'unique_together': {('billing_document', 'batch')},
            },
        ),
    ]
