# Generated by Django 6.0.1 on 2026-02-06 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0008_add_billing_line_item'),
        ('tenants', '0006_add_site_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinglineitem',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Filter batches by site', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_line_items', to='tenants.site', verbose_name='Site'),
        ),
    ]
