# Generated by Django 6.0.1 on 2026-02-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0009_add_site_to_billing_line_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingdocumentheader',
            name='vat_percentage',
            field=models.DecimalField(decimal_places=2, default=15, help_text='Value Added Tax percentage (default 15%)', max_digits=5, verbose_name='VAT %'),
        ),
    ]
