# Generated by Django 6.0.1 on 2026-02-09 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0010_billingdocumentheader_vat_percentage'),
        ('transport', '0002_deliverysite_site_transportload_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingdocumentheader',
            name='delivery_institution',
            field=models.ForeignKey(blank=True, help_text='Select the institution/location to deliver to for this client', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_headers', to='transport.deliverysite', verbose_name='Delivery Institution'),
        ),
    ]
