# Generated by Django 6.0.1 on 2026-02-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0011_billingdocumentheader_delivery_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingdocumentheader',
            name='dispatched',
            field=models.BooleanField(
                default=False,
                help_text='Mark as dispatched to create transport load (HQ only - sites use picking slip approval)',
                verbose_name='Dispatched (HQ)'
            ),
        ),
    ]

