# Generated by Django 6.0.1 on 2026-02-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0014_alter_billingdocumentheader_dispatched_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingdocumentheader',
            name='dispatched',
            field=models.BooleanField(default=False, verbose_name='Dispatched'),
        ),
    ]
