# Generated by Django 6.0.1 on 2026-02-16 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0015_alter_billingdocumentheader_dispatched'),
        ('tenants', '0009_alter_usersite_is_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorLoanCosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('production_units', models.PositiveIntegerField(default=0, verbose_name='Production Units (Month)')),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('use_as_default', models.BooleanField(default=False, help_text='Mark this record as the default investor/loan costing to use', verbose_name='Use as Default')),
                ('site', models.ForeignKey(blank=True, help_text='Site this costing belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investor_loan_costings', to='tenants.site')),
            ],
            options={
                'verbose_name': 'Investor / Loan Costing',
                'verbose_name_plural': 'Investor / Loan Costing',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='InvestorLoanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100, verbose_name='Investor / Loan Item')),
                ('item_type', models.CharField(choices=[('Investment', 'Investment'), ('Loan', 'Loan')], max_length=15, verbose_name='Type')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Amount')),
                ('monthly_payment', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monthly Payment')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='costing.investorloancosting')),
            ],
            options={
                'verbose_name': 'Investor / Loan Item',
                'verbose_name_plural': 'Investor / Loan Items',
                'ordering': ['item_type', 'item_name'],
            },
        ),
    ]
