# Generated by Django 6.0.1 on 2026-02-16 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0016_investorloancosting_investorloanitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcosting',
            name='investor_loan_costing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='costing.investorloancosting', verbose_name='Investor / Loan Costing'),
        ),
        migrations.AddField(
            model_name='productcosting',
            name='investor_loan_price_per_unit_snapshot',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Captured investor/loan price per unit. Can be updated via confirmation when default changes.', max_digits=12, null=True, verbose_name='Investor/Loan Price/Unit (Snapshot)'),
        ),
        migrations.AlterField(
            model_name='productcosting',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Selling Price = Total stock items incl. VAT + Overhead price per unit + Salary price per unit + Investor/Loan price per unit + Markup (percentage or fixed per unit).', max_digits=12, verbose_name='Selling Price'),
        ),
    ]
