# Generated by Django 6.0.1 on 2026-02-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0017_productcosting_investor_loan_costing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcosting',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Selling Price = Total stock items incl. VAT + Overhead price per unit + Salary price per unit + Investor/Loan price per unit + Markup (% or fixed per unit).', max_digits=12, verbose_name='Selling Price'),
        ),
    ]
