# Generated by Django 6.0.1 on 2026-02-16 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0018_alter_productcosting_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchcosting',
            name='investor_loan_costing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='costing.investorloancosting', verbose_name='Investor / Loan Costing'),
        ),
        migrations.AddField(
            model_name='batchcosting',
            name='investor_loan_price_per_unit_snapshot',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="Captured investor/loan price per unit at time of first save. Won't change if default investor/loan is updated.", max_digits=12, null=True, verbose_name='Investor/Loan Price/Unit (Snapshot)'),
        ),
        migrations.AlterField(
            model_name='batchcosting',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Selling Price = stock price incl VAT + overhead per unit + salary per unit + investor/loan per unit + markup.', max_digits=12, verbose_name='Selling Price'),
        ),
    ]
