# Generated by Django 6.0.1 on 2026-01-23 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
        ('manufacturing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchComponentSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(choices=[('component', 'Product Component (Packaging)'), ('main', 'Main Component (Meat)'), ('recipe', 'Recipe Item (Sauce)')], max_length=20, verbose_name='Component Type')),
                ('standard_usage_per_production_unit', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Standard Usage per Production Unit (Snapshot)')),
                ('usage_per_pallet', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Usage per Pallet (Snapshot)')),
                ('is_primary_packaging', models.BooleanField(default=False)),
                ('is_secondary_packaging', models.BooleanField(default=False)),
                ('is_pallet', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_snapshots', to='manufacturing.batch', verbose_name='Batch')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_snapshots', to='inventory.stockitem', verbose_name='Stock Item')),
            ],
            options={
                'verbose_name': 'Batch Component Snapshot',
                'verbose_name_plural': 'Batch Component Snapshots',
                'ordering': ['batch', 'component_type', 'stock_item'],
                'indexes': [models.Index(fields=['batch', 'stock_item'], name='manufacturi_batch_i_6fd597_idx')],
                'unique_together': {('batch', 'stock_item', 'component_type')},
            },
        ),
    ]
