# Generated by Django 6.0.1 on 2026-03-10 09:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchcontainer',
            name='defrost_sheet',
            field=models.FileField(blank=True, null=True, upload_to='batch_documents/defrost/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png'])], verbose_name='Defrost Sheet'),
        ),
        migrations.AlterField(
            model_name='defrostdocument',
            name='file',
            field=models.FileField(upload_to='manufacturing/defrost_sheets/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png'])], verbose_name='Defrost Sheet'),
        ),
        migrations.AlterField(
            model_name='meatproductionsummary',
            name='filling_weight_sheet',
            field=models.FileField(blank=True, null=True, upload_to='batch_documents/filling_weight/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png'])], verbose_name='Filling Weight Sheet'),
        ),
        migrations.AlterField(
            model_name='nsidocument',
            name='file',
            field=models.FileField(upload_to='manufacturing/nsi_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])], verbose_name='NSI Document (PDF)'),
        ),
        migrations.AlterField(
            model_name='productiondatedocument',
            name='file',
            field=models.FileField(upload_to='manufacturing/production_docs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png'])], verbose_name='Production Document'),
        ),
        migrations.AlterField(
            model_name='sauce',
            name='reference_file',
            field=models.FileField(blank=True, null=True, upload_to='sauce_references/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='waste',
            name='filling_sheet',
            field=models.FileField(blank=True, null=True, upload_to='sheets/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png'])], verbose_name='Filling Sheet'),
        ),
        migrations.AlterField(
            model_name='waste',
            name='final_product_packaging',
            field=models.FileField(blank=True, null=True, upload_to='packaging/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png'])], verbose_name='Final Product Packaging'),
        ),
        migrations.AlterField(
            model_name='waste',
            name='machine_production_document',
            field=models.FileField(blank=True, null=True, upload_to='pouch_docs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png'])], verbose_name='Machine Production Document'),
        ),
        migrations.AlterField(
            model_name='waste',
            name='nsi_sample_log',
            field=models.FileField(blank=True, null=True, upload_to='nsi/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png'])], verbose_name='NSI Sample Log'),
        ),
        migrations.AlterField(
            model_name='waste',
            name='retort_control_sheet',
            field=models.FileField(blank=True, null=True, upload_to='pouch_docs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png'])], verbose_name='Retort Control Sheet'),
        ),
        migrations.AlterField(
            model_name='waste',
            name='retort_sheet',
            field=models.FileField(blank=True, null=True, upload_to='sheets/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png'])], verbose_name='Retort Sheet'),
        ),
    ]
