# Generated by Django 5.2.7 on 2026-01-23 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0002_add_batch_component_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationReport',
            fields=[
            ],
            options={
                'verbose_name': 'Certification Report',
                'verbose_name_plural': 'Certification Report',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('manufacturing.batch',),
        ),
    ]
