# Generated by Django 5.2.7 on 2026-01-23 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0003_certificationreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CertificationReport',
        ),
        migrations.CreateModel(
            name='ManufacturingReport',
            fields=[
            ],
            options={
                'verbose_name': 'Manufacturing Report',
                'verbose_name_plural': 'Manufacturing Report',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('manufacturing.batch',),
        ),
    ]
