# Generated by Django 5.2.7 on 2026-01-23 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0004_delete_certificationreport_manufacturingreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockUsageReport',
            fields=[
            ],
            options={
                'verbose_name': 'Stock Usage Report',
                'verbose_name_plural': 'Stock Usage Report',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('manufacturing.batch',),
        ),
    ]
