# Generated by Django 6.0.1 on 2026-01-25 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0006_production_pk_change_and_site_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='production',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_items', to='manufacturing.production', verbose_name='Production'),
        ),
        migrations.AlterField(
            model_name='production',
            name='production_date',
            field=models.DateField(verbose_name='Production Date'),
        ),
    ]
