# Generated by Django 6.0.1 on 2026-02-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0008_batch_sku_historicalbatch_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='a_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='A-NO'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_number',
            field=models.CharField(max_length=150, primary_key=True, serialize=False, verbose_name='Production Code'),
        ),
        migrations.AlterField(
            model_name='historicalbatch',
            name='a_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='A-NO'),
        ),
        migrations.AlterField(
            model_name='historicalbatch',
            name='batch_number',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Production Code'),
        ),
    ]
