# Generated by Django 6.0.1 on 2026-02-11 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0010_fix_historicalbatch_production_id_column_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='production',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_items', to='manufacturing.production', verbose_name='Production'),
        ),
    ]
