# Generated by Django 6.0.1 on 2026-02-16 06:28
# Modified manually to handle existing id fields

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0011_change_batch_production_ondelete_setnull'),
    ]

    operations = [
        # Restore the verbose names that got removed
        migrations.AlterModelOptions(
            name='batch',
            options={'verbose_name': 'Production Batch', 'verbose_name_plural': 'Production Batches'},
        ),
        # Use SeparateDatabaseAndState to tell Django the id field exists without creating it
        migrations.SeparateDatabaseAndState(
            state_operations=[
                # Update Django's state to know about the id field on Batch
                migrations.AlterField(
                    model_name='batch',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                # Update Django's state to know about the id field on HistoricalBatch  
                migrations.AlterField(
                    model_name='historicalbatch',
                    name='id',
                    field=models.BigIntegerField(blank=True, db_index=True, verbose_name='ID'),
                ),
            ],
            database_operations=[
                # No database operations - id fields already exist from migration 0006
            ],
        ),
    ]
