# Generated by Django 6.0.1 on 2026-02-16 06:30
# No-op migration to sync Django's model state with the actual database structure

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0012_add_unique_constraint_batch'),
    ]

    operations = [
        # No operations needed - this migration exists solely to mark the model state as synced
        # The database structure is already correct from previous migrations
    ]

