# Generated by Django 6.0.1 on 2026-02-16 06:47
# Modified to only update Django's model state without touching the database

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0013_sync_final_state'),
    ]

    operations = [
        # Use SeparateDatabaseAndState to sync model state without database changes
        migrations.SeparateDatabaseAndState(
            state_operations=[
                # Sync field definitions
                migrations.AlterField(
                    model_name='batch',
                    name='batch_number',
                    field=models.CharField(max_length=150, verbose_name='Production Code'),
                ),
                migrations.AlterField(
                    model_name='historicalbatch',
                    name='batch_number',
                    field=models.CharField(max_length=150, verbose_name='Production Code'),
                ),
                migrations.AlterField(
                    model_name='historicalbatch',
                    name='id',
                    field=models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
                ),
                # Add constraint to model state (even though not enforced at DB level)
                migrations.AddConstraint(
                    model_name='batch',
                    constraint=models.UniqueConstraint(fields=('site', 'batch_number'), name='unique_batch_number_per_site'),
                ),
            ],
            database_operations=[
                # No database operations:
                # - All fields already exist from previous migrations
                # - Constraint cannot be enforced due to existing duplicate data
                # - Uniqueness validated at application level via model.clean()
            ],
        ),
    ]
