# Generated by Django 6.0.1 on 2026-02-16 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0014_finalize_batch_model_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={},
        ),
        migrations.AlterModelOptions(
            name='historicalbatch',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical batch', 'verbose_name_plural': 'historical batchs'},
        ),
    ]
