# Generated by Django 6.0.1 on 2026-02-18 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0015_alter_batch_options_alter_historicalbatch_options'),
        ('tenants', '0009_alter_usersite_is_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='meatproductionsummary',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meat_production_summaries', to='tenants.site'),
        ),
        migrations.AlterField(
            model_name='meatproductionsummary',
            name='production_date',
            field=models.DateField(verbose_name='Production Date'),
        ),
        migrations.AddConstraint(
            model_name='meatproductionsummary',
            constraint=models.UniqueConstraint(fields=('production_date', 'site'), name='unique_meat_summary_per_site_date'),
        ),
    ]
