# Generated by Django 6.0.1 on 2026-02-22 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0017_add_id_to_batch'),
    ]

    operations = [
    ]
