# Generated by Django 6.0.1 on 2026-01-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_date', models.DateField(blank=True, null=True, verbose_name='Production Date')),
                ('incident_date', models.DateField(verbose_name='Date Incident Occurred')),
                ('location', models.CharField(max_length=255, verbose_name='Where Incident Occurred')),
                ('investigation_start', models.DateField(verbose_name='Investigation From Date')),
                ('investigation_end', models.DateField(verbose_name='Investigation To Date')),
                ('report_date', models.DateField(verbose_name='Date Report Done')),
                ('responsible_person', models.CharField(max_length=255, verbose_name='Responsible Person')),
                ('management_person', models.CharField(max_length=255, verbose_name='Management Person Responsible')),
                ('description', models.TextField(blank=True, verbose_name='Incident Description')),
                ('incident_report', models.FileField(blank=True, null=True, upload_to='incident_reports/', verbose_name='Incident Report (PDF or file)')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
                'ordering': ['-incident_date', '-created'],
            },
        ),
        migrations.CreateModel(
            name='IncidentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='incident_evidence/', verbose_name='Attachment (PDF/JPEG)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Incident Attachment',
                'verbose_name_plural': 'Incident Attachments',
            },
        ),
    ]
