# Generated by Django 6.0.1 on 2026-01-22 17:30

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incident_management', '0001_initial'),
        ('manufacturing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='batch',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='production_date', chained_model_field='production_date', null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacturing.batch', verbose_name='Production Batch'),
        ),
        migrations.AddField(
            model_name='incidentattachment',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='incident_management.incident'),
        ),
    ]
