# Generated by Django 6.0.1 on 2026-02-25 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incident_management', '0001_initial'),
        ('manufacturing', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacturing.batch', verbose_name='Production Batch'),
        ),
        migrations.AddField(
            model_name='incident',
            name='import_source_incident',
            field=models.ForeignKey(blank=True, help_text='Original incident from site (HQ only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hq_imports', to='incident_management.incident', verbose_name='Source Incident'),
        ),
        migrations.AddField(
            model_name='incident',
            name='import_source_site',
            field=models.ForeignKey(blank=True, help_text='Site from which this incident was imported (HQ only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_incidents', to='tenants.site', verbose_name='Import Source Site'),
        ),
        migrations.AddField(
            model_name='incident',
            name='production',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='manufacturing.production', verbose_name='Production'),
        ),
        migrations.AddField(
            model_name='incident',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Site this incident belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='tenants.site'),
        ),
        migrations.AddField(
            model_name='incidentattachment',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='incident_management.incident'),
        ),
    ]
