# Generated by Django 6.0.1 on 2026-03-10 09:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_management', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='incident_report',
            field=models.FileField(blank=True, null=True, upload_to='incident_reports/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png'])], verbose_name='Incident Report (PDF or file)'),
        ),
        migrations.AlterField(
            model_name='incidentattachment',
            name='file',
            field=models.FileField(upload_to='incident_evidence/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])], verbose_name='Attachment (PDF/JPEG)'),
        ),
    ]
