# Generated by Django 6.0.1 on 2026-08-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_management', '0003_alter_incident_incident_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='incident_number',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Incident No.'),
        ),
    ]
