# Generated by Django 6.0.1 on 2026-02-01 17:17

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_management', '0003_incident_site'),
        ('manufacturing', '0007_production_id_alter_batch_production_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='production',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='manufacturing.production', verbose_name='Production'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='batch',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='production', chained_model_field='production', null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacturing.batch', verbose_name='Production Batch'),
        ),
    ]
