# Generated by Django 6.0.1 on 2026-02-11 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_management', '0004_incident_production_alter_incident_batch'),
        ('manufacturing', '0007_production_id_alter_batch_production_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacturing.batch', verbose_name='Production Batch'),
        ),
    ]
