# Generated by Django 6.0.1 on 2026-02-11 07:13

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incident_management', '0005_alter_incident_batch'),
        ('manufacturing', '0007_production_id_alter_batch_production_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='batch',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='production_date', chained_model_field='production_date', null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacturing.batch', verbose_name='Production Batch'),
        ),
    ]
