# Generated by Django 6.0.1 on 2026-02-11 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_management', '0006_alter_incident_batch'),
        ('manufacturing', '0010_fix_historicalbatch_production_id_column_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacturing.batch', verbose_name='Production Batch'),
        ),
    ]
