# Generated by Django 6.0.1 on 2026-02-12 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_management', '0007_alter_incident_batch'),
        ('tenants', '0008_add_site_to_unitofmeasure'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='import_source_incident',
            field=models.ForeignKey(blank=True, help_text='Original incident from site (HQ only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hq_imports', to='incident_management.incident', verbose_name='Source Incident'),
        ),
        migrations.AddField(
            model_name='incident',
            name='import_source_site',
            field=models.ForeignKey(blank=True, help_text='Site from which this incident was imported (HQ only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_incidents', to='tenants.site', verbose_name='Import Source Site'),
        ),
    ]
