# Generated by Django 6.0.1 on 2026-02-25 09:23

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commercial', '0001_initial'),
        ('costing', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institutionname', models.CharField(blank=True, max_length=255, verbose_name='Institution name')),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, default='South Africa', max_length=100)),
                ('contact_person', models.CharField(blank=True, max_length=80)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_sites', to='commercial.client', verbose_name='Client')),
                ('site', models.ForeignKey(blank=True, help_text='Site this delivery site belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_sites', to='tenants.site')),
            ],
            options={
                'verbose_name': 'Delivery site',
                'verbose_name_plural': 'Delivery sites',
            },
        ),
        migrations.CreateModel(
            name='TransportLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_date', models.DateField(blank=True, editable=False, null=True, verbose_name='Billing Date')),
                ('released_date', models.DateField(blank=True, editable=False, null=True, verbose_name='Released Date')),
                ('transport_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=12, verbose_name='Transport Cost (R)')),
                ('batch_data', models.JSONField(default=dict, editable=False, verbose_name='Batch Details')),
                ('load_number', models.CharField(default='', max_length=50, unique=True, verbose_name='Load Number')),
                ('date_loaded', models.DateField(default=django.utils.timezone.now, editable=False, verbose_name='Date Loaded')),
                ('delivery_note_documents', models.JSONField(blank=True, default=list, verbose_name='Delivery Note Documents')),
                ('namra_documents', models.JSONField(blank=True, default=list, verbose_name='NAMRA Documents')),
                ('daff_documents', models.JSONField(blank=True, default=list, verbose_name='DAFF Documents')),
                ('meat_board_documents', models.JSONField(blank=True, default=list, verbose_name='Meat Board Documents')),
                ('import_permit_documents', models.JSONField(blank=True, default=list, verbose_name='Import Permit Documents')),
                ('other_documents', models.JSONField(blank=True, default=list, verbose_name='Other Documents')),
                ('import_source_load_number', models.CharField(blank=True, help_text='Original load number from source site', max_length=50, null=True, verbose_name='Import Source Load Number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('billing_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transport_loads', to='costing.billingdocumentheader', verbose_name='Billing Document')),
                ('client', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transport_loads', to='commercial.client', verbose_name='Client')),
                ('delivery_institution', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_loads', to='transport.deliverysite', verbose_name='Delivery Institution')),
                ('import_source_site', models.ForeignKey(blank=True, help_text='Site this transport load was imported from (HQ only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_transport_loads', to='tenants.site', verbose_name='Import Source Site')),
                ('site', models.ForeignKey(blank=True, help_text='Site this transport load belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transport_loads', to='tenants.site')),
                ('transporter', models.ForeignKey(blank=True, help_text='Select transporter responsible for delivery', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loads', to='commercial.transporter', verbose_name='Transporter')),
            ],
            options={
                'verbose_name': 'Transport Load',
                'verbose_name_plural': 'Transport Loads',
                'ordering': ['-date_loaded', '-load_number'],
                'indexes': [models.Index(fields=['billing_document'], name='transport_t_billing_2331e8_idx'), models.Index(fields=['load_number'], name='transport_t_load_nu_aedda9_idx'), models.Index(fields=['released_date'], name='transport_t_release_85462b_idx')],
            },
        ),
    ]
