# Generated by Django 6.0.1 on 2026-01-25 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverysite',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Site this delivery site belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_sites', to='tenants.site'),
        ),
        migrations.AddField(
            model_name='transportload',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Site this transport load belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transport_loads', to='tenants.site'),
        ),
    ]
