# Generated by Django 6.0.1 on 2026-02-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_add_delivery_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportload',
            name='load_number',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='Load Number'),
        ),
    ]
