# Generated by Django 6.0.1 on 2026-01-22 17:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Company name')),
                ('legal_name', models.CharField(blank=True, max_length=255, verbose_name='Legal name')),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('vat_number', models.CharField(blank=True, max_length=100, verbose_name='VAT number')),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, default='South Africa', max_length=100)),
                ('payment_terms', models.TextField(blank=True)),
                ('contact_person', models.CharField(blank=True, max_length=80)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Company name')),
                ('legal_name', models.CharField(blank=True, max_length=255, verbose_name='Legal name')),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('vat_number', models.CharField(blank=True, max_length=100, verbose_name='VAT number')),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, default='South Africa', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('bank_name', models.CharField(blank=True, max_length=255)),
                ('bank_account_name', models.CharField(blank=True, max_length=255)),
                ('bank_account_number', models.CharField(blank=True, max_length=50)),
                ('bank_branch_code', models.CharField(blank=True, max_length=50)),
                ('currency', models.CharField(blank=True, max_length=10, verbose_name='Currency')),
                ('logo', models.ImageField(blank=True, help_text='Logo used on invoices/quotes.', null=True, upload_to='company/logo/')),
                ('billing_template', models.FileField(blank=True, help_text='Single billing template used for invoice/quote/proforma.', null=True, upload_to='company/templates/billing/')),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Company details',
                'verbose_name_plural': 'Company details',
            },
        ),
        migrations.CreateModel(
            name='StandardTransportRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('R', 'R'), ('NAD', 'NAD'), ('$', '$'), ('€', '€')], default='R', max_length=3)),
                ('from_location', models.CharField(max_length=120, verbose_name='From')),
                ('to_location', models.CharField(max_length=120, verbose_name='To')),
                ('amount_excl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Amount excl')),
            ],
            options={
                'verbose_name': 'Standard transport rate',
                'verbose_name_plural': 'Standard transport rates',
                'ordering': ['from_location', 'to_location', 'currency'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('contact_person', models.CharField(blank=True, max_length=80)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Transporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('contact_person', models.CharField(blank=True, max_length=80)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_name', models.CharField(max_length=80, verbose_name='Warehouse name')),
                ('size_m2', models.DecimalField(blank=True, decimal_places=2, help_text='Total floor area in square meters.', max_digits=10, null=True, verbose_name='Size m²')),
                ('standard_rate_per_m2_per_month', models.DecimalField(blank=True, decimal_places=2, help_text='Base rental rate per square meter per month.', max_digits=10, null=True, verbose_name='Standard rate per m² / month')),
                ('total_rent_per_month', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly rent for this warehouse.', max_digits=12, null=True, verbose_name='Total rent per month')),
                ('lease_expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry date of lease')),
                ('manager', models.CharField(blank=True, max_length=80)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, default='South Africa', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
            ],
        ),
    ]
