# Generated by Django 6.0.1 on 2026-02-25 09:23

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commercial', '0001_initial'),
        ('inventory', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.stockcategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Site this supplier belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='tenants.site'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='sub_category',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='category', chained_model_field='category', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.stocksubcategory', verbose_name='Sub Category'),
        ),
        migrations.AddField(
            model_name='transporter',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Site this transporter belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transporters', to='tenants.site'),
        ),
        migrations.AddField(
            model_name='standardtransportrate',
            name='transporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standard_rates', to='commercial.transporter'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Site this warehouse belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='tenants.site'),
        ),
    ]
