# Generated by Django 6.0.1 on 2026-03-10 09:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='admin_background',
            field=models.ImageField(blank=True, help_text='Background image displayed on the admin dashboard (JPEG/PNG).', null=True, upload_to='company/background/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])], verbose_name='Admin Background Image'),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='billing_template',
            field=models.FileField(blank=True, help_text='Single billing template used for invoice/quote/proforma.', null=True, upload_to='company/templates/billing/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo used on invoices/quotes.', null=True, upload_to='company/logo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='po_template',
            field=models.FileField(blank=True, help_text='Template document (.docx) for generating purchase orders.', null=True, upload_to='company/templates/po/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf'])], verbose_name='Purchase Order Template'),
        ),
    ]
