# Generated by Django 6.0.1 on 2026-01-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='po_template',
            field=models.FileField(blank=True, help_text='Template document (.docx) for generating purchase orders.', null=True, upload_to='company/templates/po/', verbose_name='Purchase Order Template'),
        ),
    ]
