# Generated by Django 5.2.7 on 2026-01-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0003_add_purchase_order_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='admin_background',
            field=models.ImageField(blank=True, help_text='Background image displayed on the admin dashboard (JPEG/PNG).', null=True, upload_to='company/background/', verbose_name='Admin Background Image'),
        ),
    ]
