# Generated by Django 6.0.1 on 2026-01-25 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0004_add_admin_background'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Site this client belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='tenants.site'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Site this supplier belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='tenants.site'),
        ),
        migrations.AddField(
            model_name='transporter',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Site this transporter belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transporters', to='tenants.site'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Site this warehouse belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='tenants.site'),
        ),
    ]
